apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- service-backend.yaml
- ingress.yaml
- persistentvolumeclaim.yaml
- namespace.yaml
images:
- name: IMAGEBACKEND
  newName: jammeri/backend:4.6.3
- name: IMAGEFRONTEND
  newName: jammeri/project:4.2.5
