apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: project
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
